<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('cita', 'doctrine');

/**
 * Basecita
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $paciente_id
 * @property integer $doctor_id
 * @property timestamp $fecha_hora
 * @property string $motivo
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method integer   getPacienteId()  Returns the current record's "paciente_id" value
 * @method integer   getDoctorId()    Returns the current record's "doctor_id" value
 * @method timestamp getFechaHora()   Returns the current record's "fecha_hora" value
 * @method string    getMotivo()      Returns the current record's "motivo" value
 * @method cita      setId()          Sets the current record's "id" value
 * @method cita      setPacienteId()  Sets the current record's "paciente_id" value
 * @method cita      setDoctorId()    Sets the current record's "doctor_id" value
 * @method cita      setFechaHora()   Sets the current record's "fecha_hora" value
 * @method cita      setMotivo()      Sets the current record's "motivo" value
 * @property  $
 * @property  $
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecita extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cita');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('paciente_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('doctor_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('fecha_hora', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('motivo', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Paciente', array(
             'local' => 'paciente_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Doctor', array(
             'local' => 'doctor_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}