<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('doctor', 'doctrine');

/**
 * Basedoctor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $apellido
 * @property string $especialidad
 * @property string $licencia
 * 
 * @method integer getId()           Returns the current record's "id" value
 * @method string  getNombre()       Returns the current record's "nombre" value
 * @method string  getApellido()     Returns the current record's "apellido" value
 * @method string  getEspecialidad() Returns the current record's "especialidad" value
 * @method string  getLicencia()     Returns the current record's "licencia" value
 * @method doctor  setId()           Sets the current record's "id" value
 * @method doctor  setNombre()       Sets the current record's "nombre" value
 * @method doctor  setApellido()     Sets the current record's "apellido" value
 * @method doctor  setEspecialidad() Sets the current record's "especialidad" value
 * @method doctor  setLicencia()     Sets the current record's "licencia" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basedoctor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('doctor');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('apellido', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('especialidad', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('licencia', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}