<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('paciente', 'doctrine');

/**
 * Basepaciente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property string $apellido
 * @property string $documento
 * @property string $telefono
 * @property string $email
 * 
 * @method integer  getId()        Returns the current record's "id" value
 * @method string   getNombre()    Returns the current record's "nombre" value
 * @method string   getApellido()  Returns the current record's "apellido" value
 * @method string   getDocumento() Returns the current record's "documento" value
 * @method string   getTelefono()  Returns the current record's "telefono" value
 * @method string   getEmail()     Returns the current record's "email" value
 * @method paciente setId()        Sets the current record's "id" value
 * @method paciente setNombre()    Sets the current record's "nombre" value
 * @method paciente setApellido()  Sets the current record's "apellido" value
 * @method paciente setDocumento() Sets the current record's "documento" value
 * @method paciente setTelefono()  Sets the current record's "telefono" value
 * @method paciente setEmail()     Sets the current record's "email" value
 * 
 * @package    symfony
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basepaciente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('paciente');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('apellido', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('documento', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 20,
             ));
        $this->hasColumn('telefono', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('email', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}