version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: reto_medico_web
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - symfony-net

  db:
    image: mysql:5.7
    container_name: reto_medico_db
    environment:
      MYSQL_DATABASE: reto_software_medico
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - symfony-net

networks:
  symfony-net:
    driver: bridge

volumes:
  db_data: