<?php

/**
 * citaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class citaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object citaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('cita');
    }
}