<?php

/**
 * database_existsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class database_existsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object database_existsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('database_exists');
    }
}