<?php

/**
 * doctorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class doctorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object doctorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('doctor');
    }
}