<?php

/**
 * pacienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class pacienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object pacienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('paciente');
    }
}