dispositivo:
    _attributes: { phpName: Dispositivo }
    id:          ~
    anio:        { type: integer, required: true }
    memoria:     { type: varchar, size: 50, required: true }
    fecha_mantenimiento: { type: date, required: true }
    created_at:  ~  